# Generated by Django 4.0.4 on 2022-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
